Pytorch Practise

In [ ]:
import torch
import numpy as np

In [ ]:
if torch.cuda.is_available():
 mydevice =torch.device('cuda')
else:
 mydevice =torch.device('cpu')
print('1D tensor')
t1=torch.tensor([2,4,6,8], device =mydevice,dtype=torch.float32,requires_grad=True)
print(t1)
print(f"device:{t1.device}\n")
print(f"grand:{t1.requires_grad}\n")
print(f"type:{t1.dtype}\n")
print(f"shape:{t1.shape}\n")
print(f"size:{t1.size()}\n")
print(f"dim:{t1.ndim}\n")
print(f"total number:{t1.numel()}\n")
print("----------------------------------------")
print('different type of tensor with numpy array')
n = np.array([2.,4.,6.,8.])
print(n,n.dtype)
print("----------------------------------------")
print('2D tensor')
t2=torch.tensor([(1,2,3),(5,7,8),(6,9,2)])
print(t2)
print(f"device:{t2.device}\n")
print(f"grand:{t2.requires_grad}\n")
print(f"type:{t2.dtype}\n")
print(f"shape:{t2.shape}\n")
print(f"size:{t2.size()}\n")
print(f"dim:{t2.ndim}\n")
print(f"total number:{t2.numel()}\n")
print("----------------------------------------")
print('3D tensor')
t3=torch.tensor([
    [[1,2,3],[4,5,6]],
    [[0,0,0],[0,0,0]]

    ])
print(t3)
print(f"device:{t3.device}\n")
print(f"grand:{t3.requires_grad}\n")
print(f"type:{t3.dtype}\n")
print(f"shape:{t3.shape}\n")
print(f"size:{t3.size()}\n")
print(f"dim:{t3.ndim}\n")
print(f"total number:{t3.numel()}\n")

In [ ]:

def create_tensors_with_arange_and_linspace():

    # torch.arange(stop)
    # Creates a 1D tensor with a sequence of numbers from 0 to 'stop' (exclusive)
    print("1. torch.arange(5)")
    t1 = torch.arange(5)
    print(f"Tensor: {t1}")
    print(f"Shape: {t1.shape}\n")

    # torch.arange(start, stop)
    # Creates a 1D tensor with numbers from 'start' to 'stop' (exclusive)
    print("2. torch.arange(2, 8)")
    t2 = torch.arange(2, 8)
    print(f"Tensor: {t2}")
    print(f"Shape: {t2.shape}\n")

    # torch.arange(start, stop, step)
    # Creates a 1D tensor with numbers from 'start' to 'stop' (exclusive) with a given 'step'
    print("3. torch.arange(0, 10, 2)")
    t3 = torch.arange(0, 10, 2)
    print(f"Tensor: {t3}")
    print(f"Shape: {t3.shape}\n")

    print("--- Using torch.linspace() ---")

    # torch.linspace(start, stop, num)
    # Creates a 1D tensor with 'num' evenly spaced numbers between 'start' and 'stop' (inclusive)
    print("1. torch.linspace(0, 10, 5)")
    t4 = torch.linspace(0, 10, 5)
    print(f"Tensor: {t4}")
    print(f"Shape: {t4.shape}\n")

    print("2. torch.linspace(1, 10, 10)")
    t5 = torch.linspace(1, 10, 10)
    print(f"Tensor: {t5}")
    print(f"Shape: {t5.shape}\n")

if __name__ == "__main__":
    create_tensors_with_arange_and_linspace()


Random generation with pytorch

In [ ]:
import torch

t1= torch.linspace(1,5,5)

print(t1,t.dtype)
print("----------------------------------------")
t= torch.empty(1,2)

print(t1,t.size())
print("----------------------------------------")
t2= torch.ones(3,2,5)

print(t2,t.size())
print("----------------------------------------")

t3= torch.tensor([[1,2,3],[4,5,6]])
a= torch.ones_like(t3)
print(t3,t3.size())
print(a,a.size())
print("----------------------------------------")
n=5
t= torch.randperm(n)
t
print("----------------------------------------")
import torch

from matplotlib import pyplot as plt

t= torch.randn(2,100)

print(t.size())

plt.plot(t[0,:],t[1,:],'ob')

plt.show()

print("----------------------------------------")

t= torch.randn(2,5)

print(t.size())

print(t)

ind= torch.randperm(t.size(1))

print(ind)

sel= t[:,ind[:2]]

print(sel)

indexing in tensor

In [ ]:
import torch
t= torch.randn(2,5)

print(t.size())

print(t)

ind= torch.randperm(t.size(1))

print(ind)

sel= t[:,ind[:2]]

print(sel)

print("----------------------------------------")
# Original tensor
original_tensor = torch.tensor([4, -8, 5, 3, -2, 1])
print(f"Original Tensor: {original_tensor}\n")

# Flip the tensor along the only dimension (dimension 0)
flipped_tensor = torch.flip(original_tensor, dims=[0])
print(f"Flipped Tensor: {flipped_tensor}")

flip for 2D tensor

In [ ]:
import torch


print("----------------------------------------")

# Create a 2D tensor
original_tensor = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("Original Tensor:")
print(f"{original_tensor}\n")

# Flip the tensor vertically (along dimension 0, the rows)
flipped_rows = torch.flip(original_tensor, dims=[0])
print("Flipped Vertically (rows flipped):")
print(f"{flipped_rows}\n")

# Flip the tensor horizontally (along dimension 1, the columns)
flipped_columns = torch.flip(original_tensor, dims=[1])
print("Flipped Horizontally (columns flipped):")
print(f"{flipped_columns}\n")

# Flip the tensor both vertically and horizontally
flipped_both = torch.flip(original_tensor, dims=[0, 1])
print("Flipped Both Vertically and Horizontally:")
print(f"{flipped_both}")


Rounding method in pytorch

In [ ]:
import torch

def demonstrate_rounding_methods():
    """
    Demonstrates different ways to round numbers in a PyTorch tensor.
    """
    # Create a tensor with a mix of positive and negative float values
    t = torch.tensor([2.3, 2.7, -1.2, -1.8, 4.5, -3.5])
    print(f"Original Tensor:\n{t}\n")

    # Round to the nearest integer
    rounded_t = torch.round(t)
    print(f"torch.round(t): rounds to nearest integer")
    print(f"Result: {rounded_t}\n")

    # Round up to the nearest integer
    ceil_t = torch.ceil(t)
    print(f"torch.ceil(t): rounds up")
    print(f"Result: {ceil_t}\n")

    # Round down to the nearest integer
    floor_t = torch.floor(t)
    print(f"torch.floor(t): rounds down")
    print(f"Result: {floor_t}\n")

    # Truncate the decimal part (round towards zero)
    trunc_t = torch.trunc(t)
    print(f"torch.trunc(t): truncates (rounds towards zero)")
    print(f"Result: {trunc_t}\n")

if __name__ == "__main__":
    demonstrate_rounding_methods()


Squeeze

In [12]:
import torch

# Create a tensor with multiple dimensions of size 1
x = torch.zeros(2, 1, 3, 1, 4)
print(x)
print(f"Original tensor shape: {x.shape},{x.ndim}")

# Use squeeze() without specifying a dimension
y = torch.squeeze(x)
print(y)
print(f"Shape after squeezing all dimensions of size 1: {y.shape}")

# Create a new tensor to demonstrate squeezing a specific dimension
z = torch.zeros(1, 5, 1, 2)
print(f"\nOriginal tensor shape: {z.shape},{z.ndim}")

# Squeeze only the first dimension (index 0)
# Note: The dimension at index 2 will remain because it was not specified.
w = torch.squeeze(z, dim=0)
print(f"Shape after squeezing only dimension 0: {w.shape},{w.ndim}")

# Squeeze only the third dimension (index 2)
v = torch.squeeze(z, dim=2)
print(f"Shape after squeezing only dimension 2: {v.shape},{v.ndim}")

tensor([[[[[0., 0., 0., 0.]],

          [[0., 0., 0., 0.]],

          [[0., 0., 0., 0.]]]],



        [[[[0., 0., 0., 0.]],

          [[0., 0., 0., 0.]],

          [[0., 0., 0., 0.]]]]])
Original tensor shape: torch.Size([2, 1, 3, 1, 4]),5
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape after squeezing all dimensions of size 1: torch.Size([2, 3, 4])

Original tensor shape: torch.Size([1, 5, 1, 2]),4
Shape after squeezing only dimension 0: torch.Size([5, 1, 2]),3
Shape after squeezing only dimension 2: torch.Size([1, 5, 2]),3


Transpose in pytorch

In [ ]:
# This script demonstrates the use of torch.transpose()
# to swap dimensions of a tensor in PyTorch.

import torch

def demonstrate_transpose(tensor, dim0, dim1):
    """
    Demonstrates the transpose operation on a given tensor.

    Args:
        tensor (torch.Tensor): The input tensor.
        dim0 (int): The first dimension to swap.
        dim1 (int): The second dimension to swap.
    """
    print(f"Original Tensor:\n{tensor}")
    print(f"Original Shape: {tensor.shape}\n")

    # Perform the transpose operation
    transposed_tensor = torch.transpose(tensor, dim0, dim1)

    print(f"Transposed Tensor (swapping dim {dim0} and dim {dim1}):\n{transposed_tensor}")
    print(f"New Shape: {transposed_tensor.shape}\n")

    # Note on underlying storage: transpose() returns a new tensor that shares
    # the same underlying data storage with the original tensor. This means
    # that an in-place modification to one will affect the other.
    print("-" * 30)

# --- Example 1: Transposing a 2D Tensor (Matrix) ---
print("--- Example 1: 2D Tensor Transpose (like a matrix) ---")
# A 2x3 tensor
tensor_2d = torch.tensor([[1, 2, 3],
                          [4, 5, 6]])

# Swapping dimension 0 (rows) and dimension 1 (columns)
demonstrate_transpose(tensor_2d, 0, 1)

# --- Example 2: Transposing a 3D Tensor ---
print("--- Example 2: 3D Tensor Transpose ---")
# A 2x3x4 tensor
tensor_3d = torch.arange(24).reshape(2, 3, 4)

# Swapping dimension 0 (the 'batch' or 'z-axis') and dimension 2 (the 'columns' or 'x-axis')
# The shape will change from (2, 3, 4) to (4, 3, 2)
demonstrate_transpose(tensor_3d, 0, 2)


# --- Example 3: Comparison with .permute() ---
print("--- Example 3: Comparison with .permute() ---")
# .permute() is a more general version of transpose()
# It allows you to rearrange all dimensions in any order.

tensor_3d_permute = torch.arange(24).reshape(2, 3, 4)
print(f"Original Tensor for permute:\n{tensor_3d_permute}")
print(f"Original Shape: {tensor_3d_permute.shape}\n")

# Same operation as Example 2, but using .permute()
# The original dimensions were at indices [0, 1, 2].
# We want to swap dim 0 and dim 2, so the new order is [2, 1, 0].
permuted_tensor = tensor_3d_permute.permute(2, 1, 0)
print(f"Permuted Tensor (new order [2, 1, 0]):\n{permuted_tensor}")
print(f"New Shape: {permuted_tensor.shape}")


Reshape

In [ ]:
# This script demonstrates the use of torch.reshape()
# and the concept of memory contiguity in PyTorch.

import torch

def demonstrate_reshape(tensor):
    """
    Shows how reshape() works on a tensor.

    Args:
        tensor (torch.Tensor): The input tensor.
    """
    print(f"Original Tensor:\n{tensor}")
    print(f"Original Shape: {tensor.shape}")
    print(f"Is Contiguous: {tensor.is_contiguous()}\n")

    # Reshape the tensor into a new shape (e.g., from 2x3 to 3x2)
    try:
        reshaped_tensor = tensor.reshape(3, 2)
        print(f"Reshaped Tensor:\n{reshaped_tensor}")
        print(f"New Shape: {reshaped_tensor.shape}")
        print(f"Is Contiguous: {reshaped_tensor.is_contiguous()}\n")
    except RuntimeError as e:
        print(f"Could not reshape due to a RuntimeError:\n{e}")

    print("-" * 30)

# --- Example 1: Reshaping a simple, contiguous tensor ---
print("--- Example 1: Reshaping a Contiguous Tensor ---")
# A simple 2x3 tensor is contiguous by default
contiguous_tensor = torch.arange(6).reshape(2, 3)
demonstrate_reshape(contiguous_tensor)

"""
--- Example 1: Reshaping a Contiguous Tensor ---
Original Tensor:
tensor([[0, 1, 2],
        [3, 4, 5]])
Original Shape: torch.Size([2, 3])
Is Contiguous: True

Reshaped Tensor:
tensor([[0, 1],
        [2, 3],
        [4, 5]])
New Shape: torch.Size([3, 2])
Is Contiguous: True
"""

# --- Example 2: The effect of transpose() on contiguity ---
print("--- Example 2: Reshaping a Transposed (Non-Contiguous) Tensor ---")
# First, create a tensor and transpose it.
# This swaps the dimensions but does NOT make the data contiguous in memory.
transposed_tensor = contiguous_tensor.transpose(0, 1)

# Note that the order of elements has been changed.
print(f"Tensor after transpose(0, 1):\n{transposed_tensor}")
print(f"Shape: {transposed_tensor.shape}")
print(f"Is Contiguous: {transposed_tensor.is_contiguous()}\n")

# Now, try to reshape this non-contiguous tensor.
# PyTorch will automatically create a contiguous copy in the background.
# It's an important distinction for performance.
print("Attempting to reshape the non-contiguous tensor...")
reshaped_from_transposed = transposed_tensor.reshape(2, 3)
print(f"Reshaped tensor from transposed one:\n{reshaped_from_transposed}")
print(f"New Shape: {reshaped_from_transposed.shape}")
print(f"Is Contiguous: {reshaped_from_transposed.is_contiguous()}\n")
print("-" * 30)

"""
--- Example 2: Reshaping a Transposed (Non-Contiguous) Tensor ---
Tensor after transpose(0, 1):
tensor([[0, 3],
        [1, 4],
        [2, 5]])
Shape: torch.Size([3, 2])
Is Contiguous: False

Attempting to reshape the non-contiguous tensor...
Reshaped tensor from transposed one:
tensor([[0, 3, 1],
        [4, 2, 5]])
New Shape: torch.Size([2, 3])
Is Contiguous: True
"""

# --- Example 3: Making a tensor contiguous explicitly ---
print("--- Example 3: Using .contiguous() before reshape() ---")
# For clarity and performance, it's often best to make a tensor contiguous yourself.
# This forces the memory to be rearranged before the reshape operation.
tensor_to_reshape = contiguous_tensor.transpose(0, 1).contiguous()

print(f"Original tensor (transposed then contiguous):\n{tensor_to_reshape}")
print(f"Shape: {tensor_to_reshape.shape}")
print(f"Is Contiguous: {tensor_to_reshape.is_contiguous()}\n")

"""
--- Example 3: Using .contiguous() before reshape() ---
Original tensor (transposed then contiguous):
tensor([[0, 3],
        [1, 4],
        [2, 5]])
Shape: torch.Size([3, 2])
Is Contiguous: True

Tensor after .contiguous().reshape(2, 3):
tensor([[0, 3, 1],
        [4, 2, 5]])
New Shape: torch.Size([2, 3])
Is Contiguous: True

--- Special Case: Using -1 in reshape() ---
Original 3D tensor:
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
Original Shape: torch.Size([2, 2, 3])
Flattened tensor using reshape(-1):
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
New Shape: torch.Size([12])
"""

# Now reshape() is guaranteed to be a fast, zero-copy operation.
explicit_reshaped = tensor_to_reshape.reshape(2, 3)
print(f"Tensor after .contiguous().reshape(2, 3):\n{explicit_reshaped}")
print(f"New Shape: {explicit_reshaped.shape}")
print(f"Is Contiguous: {explicit_reshaped.is_contiguous()}\n")

# --- Special case: using -1 ---
print("--- Special Case: Using -1 in reshape() ---")
# PyTorch can infer one dimension's size if you pass -1.
# This is very useful when you want to flatten a tensor.
tensor_for_flatten = torch.arange(12).reshape(2, 2, 3)
print(f"Original 3D tensor:\n{tensor_for_flatten}")
print(f"Original Shape: {tensor_for_flatten.shape}")
flattened_tensor = tensor_for_flatten.reshape(-1) # Flattens to a 1D tensor
print(f"Flattened tensor using reshape(-1):\n{flattened_tensor}")
print(f"New Shape: {flattened_tensor.shape}")

Ravel in pytorch

In [ ]:
# This script demonstrates the use of torch.ravel() to flatten a tensor
# and explores how it handles contiguous and non-contiguous data.

import torch

# --- Part 1: Ravel on a contiguous tensor ---
# A simple tensor created with arange() is contiguous by default.
print("--- Example 1: Ravel on a Contiguous Tensor ---")
contiguous_tensor = torch.arange(12).reshape(3, 4)
print(f"Original Tensor (contiguous):\n{contiguous_tensor}")
print(f"Original Shape: {contiguous_tensor.shape}")
print(f"Is Contiguous: {contiguous_tensor.is_contiguous()}\n")

# Use ravel() to flatten the tensor. Since it's contiguous,
# this operation returns a view (no data is copied).
raveled_tensor = torch.ravel(contiguous_tensor)
print(f"Raveled Tensor:\n{raveled_tensor}")
print(f"Raveled Shape: {raveled_tensor.shape}\n")

# You can see they share the same memory by modifying one.
raveled_tensor[0] = 99
print("Original Tensor after modifying raveled_tensor:")
print(contiguous_tensor)
print("-" * 30)


# --- Part 2: Ravel on a non-contiguous tensor ---
# We can make a tensor non-contiguous by using an operation like transpose().
print("--- Example 2: Ravel on a Non-Contiguous Tensor ---")
non_contiguous_tensor = contiguous_tensor.transpose(0, 1)
print(f"Transposed Tensor (now non-contiguous):\n{non_contiguous_tensor}")
print(f"Shape: {non_contiguous_tensor.shape}")
print(f"Is Contiguous: {non_contiguous_tensor.is_contiguous()}\n")

# When ravel() is used on a non-contiguous tensor, a copy of the data is made
# to arrange it contiguously in memory.
raveled_non_contiguous = torch.ravel(non_contiguous_tensor)
print(f"Raveled Non-Contiguous Tensor:\n{raveled_non_contiguous}")
print(f"Raveled Shape: {raveled_non_contiguous.shape}\n")

# Modifying the new raveled tensor now does NOT affect the original.
raveled_non_contiguous[0] = 100
print("Transposed Tensor after modifying its raveled version:")
print(non_contiguous_tensor)
print("-" * 30)

# --- Part 3: Comparison with other flattening methods ---
print("--- Example 3: Comparison with reshape(-1) and flatten() ---")
tensor_to_compare = torch.arange(6).reshape(2, 3)

# reshape(-1) is the most common and concise way to flatten a tensor.
reshaped_flat = tensor_to_compare.reshape(-1)
print(f"Using tensor.reshape(-1):\n{reshaped_flat}")

# flatten() is a more descriptive name for the operation and is functionally
# identical to ravel().
flattened_tensor = torch.flatten(tensor_to_compare)
print(f"Using torch.flatten():\n{flattened_tensor}")

# For a 2D tensor, the .T attribute is a quick way to transpose.
transposed_T = tensor_to_compare.T
print(f"Using tensor.T (transposed):\n{transposed_T}")

Flatten in pytorch

In [ ]:
# This script demonstrates the use of torch.flatten()
# for reshaping tensors, including its optional arguments.

import torch

# --- Example 1: Flattening the entire tensor ---
# Create a 3D tensor, which could represent a batch of two 3x4 images.
print("--- Example 1: Flattening a 3D tensor to 1D ---")
tensor_3d = torch.arange(24).reshape(2, 3, 4)
print(f"Original Tensor:\n{tensor_3d}")
print(f"Original Shape: {tensor_3d.shape}\n")

# Flatten the entire tensor. This is the default behavior.
flattened_tensor = torch.flatten(tensor_3d)
print(f"Flattened Tensor:\n{flattened_tensor}")
print(f"New Shape: {flattened_tensor.shape}\n")
print("-" * 30)


# --- Example 2: Flattening with start_dim and end_dim ---
# This is a common use case in neural networks where the first
# dimension is the batch size and should not be flattened.
print("--- Example 2: Flattening with a specified start_dim ---")
# Let's use the same 3D tensor from above.
# We want to flatten the last two dimensions (3x4) while keeping the
# first dimension (batch size of 2) separate.
flattened_with_dim = torch.flatten(tensor_3d, start_dim=1)
print(f"Original Tensor (with batch dim):\n{tensor_3d}")
print(f"Original Shape: {tensor_3d.shape}\n")

print(f"Flattened from start_dim=1:\n{flattened_with_dim}")
print(f"New Shape: {flattened_with_dim.shape}\n")
print("-" * 30)


# --- Example 3: Flattening a non-contiguous tensor ---
print("--- Example 3: Flattening a Non-Contiguous Tensor ---")
# First, create a non-contiguous tensor using transpose().
non_contiguous_tensor = tensor_3d.transpose(1, 2)
print(f"Transposed Tensor (now non-contiguous):\n{non_contiguous_tensor}")
print(f"Shape: {non_contiguous_tensor.shape}")
print(f"Is Contiguous: {non_contiguous_tensor.is_contiguous()}\n")

# When we flatten this tensor, a copy will be created behind the scenes
# to make the data contiguous for the new flattened shape.
flattened_non_contiguous = torch.flatten(non_contiguous_tensor)
print(f"Flattened non-contiguous tensor:\n{flattened_non_contiguous}")
print(f"New Shape: {flattened_non_contiguous.shape}")
print("-" * 30)

# --- Example 4: Comparison with other methods ---
print("--- Example 4: Comparing flatten() with reshape(-1) and ravel() ---")
tensor_to_compare = torch.arange(6).reshape(2, 3)

# Using .reshape(-1)
reshaped_flat = tensor_to_compare.reshape(-1)
print(f"Using tensor.reshape(-1):\n{reshaped_flat}")

# Using torch.ravel()
raveled_tensor = torch.ravel(tensor_to_compare)
print(f"Using torch.ravel():\n{raveled_tensor}")

# These methods are all functionally very similar for simple flattening.
# The choice often comes down to personal preference or coding style.


example of flatten wirh different start_dim and end_dim

In [16]:
# This script demonstrates the use of torch.flatten()
# for reshaping tensors, including its optional arguments.

import torch

# --- Example 1: Flattening the entire tensor ---
# Create a 3D tensor, which could represent a batch of two 3x4 images.
print("--- Example 1: Flattening a 3D tensor to 1D ---")
tensor_3d = torch.arange(24).reshape(2, 3, 4)
print(f"Original Tensor:\n{tensor_3d}")
print(f"Original Shape: {tensor_3d.shape}\n")

# Flatten the entire tensor. This is the default behavior.
flattened_tensor = torch.flatten(tensor_3d)
print(f"Flattened Tensor:\n{flattened_tensor}")
print(f"New Shape: {flattened_tensor.shape}\n")
print("-" * 30)


# --- Example 2: Flattening with start_dim and end_dim ---
# This is a common use case in neural networks where the first
# dimension is the batch size and should not be flattened.
print("--- Example 2: Flattening with a specified start_dim ---")
# Let's use the same 3D tensor from above.
# We want to flatten the last two dimensions (3x4) while keeping the
# first dimension (batch size of 2) separate.
flattened_with_dim = torch.flatten(tensor_3d, start_dim=1)
print(f"Original Tensor (with batch dim):\n{tensor_3d}")
print(f"Original Shape: {tensor_3d.shape}\n")

print(f"Flattened from start_dim=1:\n{flattened_with_dim}")
print(f"New Shape: {flattened_with_dim.shape}\n")
print("-" * 30)


# --- Example 3: Flattening a non-contiguous tensor ---
print("--- Example 3: Flattening a Non-Contiguous Tensor ---")
# First, create a non-contiguous tensor using transpose().
non_contiguous_tensor = tensor_3d.transpose(1, 2)
print(f"Transposed Tensor (now non-contiguous):\n{non_contiguous_tensor}")
print(f"Shape: {non_contiguous_tensor.shape}")
print(f"Is Contiguous: {non_contiguous_tensor.is_contiguous()}\n")

# When we flatten this tensor, a copy will be created behind the scenes
# to make the data contiguous for the new flattened shape.
flattened_non_contiguous = torch.flatten(non_contiguous_tensor)
print(f"Flattened non-contiguous tensor:\n{flattened_non_contiguous}")
print(f"New Shape: {flattened_non_contiguous.shape}")
print("-" * 30)

# --- Example 4: Comparison with other methods ---
print("--- Example 4: Comparing flatten() with reshape(-1) and ravel() ---")
tensor_to_compare = torch.arange(6).reshape(2, 3)

# Using .reshape(-1)
reshaped_flat = tensor_to_compare.reshape(-1)
print(f"Using tensor.reshape(-1):\n{reshaped_flat}")

# Using torch.ravel()
raveled_tensor = torch.ravel(tensor_to_compare)
print(f"Using torch.ravel():\n{raveled_tensor}")

# These methods are all functionally very similar for simple flattening.
# The choice often comes down to personal preference or coding style.
print("-" * 30)


# --- Example 5: Flattening a 4D tensor with various dims ---
# This demonstrates the flexibility of start_dim and end_dim.
print("--- Example 5: Flattening a 4D Tensor (e.g., a batch of images) ---")
# Create a 4D tensor with dimensions: (batch_size, channels, height, width)
# A tensor with shape (32, 1, 5, 5) represents a batch of 32 grayscale 5x5 images.
tensor_4d = torch.arange(32 * 1 * 5 * 5).reshape(32, 1, 5, 5)
print(f"Original 4D Tensor shape: {tensor_4d.shape}\n")

# Case 5.1: Flatten everything after the batch dimension.
# This is a common operation before a linear layer.
flattened_case1 = torch.flatten(tensor_4d, start_dim=1)
print(f"Flattened from start_dim=1 (collapsing channel, height, width):")
print(f"New Shape: {flattened_case1.shape}\n")

# Case 5.2: Flatten only the height and width dimensions.
# Here, we keep the batch and channel dimensions separate.
# The -1 index refers to the last dimension.
flattened_case2 = torch.flatten(tensor_4d, start_dim=2, end_dim=-1)
print(f"Flattened from start_dim=2 to end_dim=-1 (collapsing height and width):")
print(f"New Shape: {flattened_case2.shape}\n")

# Case 5.3: Flatten the entire tensor into a 1D vector.
# This is useful for passing the whole tensor to a function that expects a 1D input.
flattened_case3 = torch.flatten(tensor_4d)
print(f"Flattening the entire tensor:")
print(f"New Shape: {flattened_case3.shape}\n")


--- Example 1: Flattening a 3D tensor to 1D ---
Original Tensor:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
Original Shape: torch.Size([2, 3, 4])

Flattened Tensor:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
New Shape: torch.Size([24])

------------------------------
--- Example 2: Flattening with a specified start_dim ---
Original Tensor (with batch dim):
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
Original Shape: torch.Size([2, 3, 4])

Flattened from start_dim=1:
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
New Shape: torch.Size([2, 12])

------------------------------
--- Example 3: Flattening a Non-Con