In [ ]:
# This script demonstrates how to reshape a 1D tensor
# of 24 numbers into a 2D tensor of shape 6x4.

import torch

# Create a 1D tensor with 24 elements.
# The shape is (24,)
original_tensor = torch.arange(12)
print("Original 1D Tensor:")
print(f"Shape: {original_tensor.shape}")
print(original_tensor)
print("-" * 30)

# Reshape the 1D tensor into a 2D tensor with 6 rows and 4 columns.
# The product of the new dimensions (6 * 4 = 24) must match
# the number of elements in the original tensor.
reshaped_tensor = original_tensor.reshape(3, 4)
print("Reshaped 2D Tensor (6x4):")
print(f"Shape: {reshaped_tensor.shape}")
print(reshaped_tensor)

Original 1D Tensor:
Shape: torch.Size([12])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
------------------------------
Reshaped 2D Tensor (6x4):
Shape: torch.Size([3, 4])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


torch.cat

In [ ]:
# This script demonstrates the use of torch.cat() for concatenating tensors.
import torch
# --- Example : Concatenating 1D Tensors ---
# Create two 1D tensors
tensor1_1d = torch.tensor([1, 2, 3])
tensor2_1d = torch.tensor([4, 5, 6])
print("--- Example 1: 1D Tensors ---")
print(f"Tensor 1: {tensor1_1d}")
print(f"Tensor 2: {tensor2_1d}\n")

# Concatenate along the single dimension (dim=0)
concatenated_1d = torch.cat((tensor1_1d, tensor2_1d), dim=0)
print(f"Concatenated 1D Tensor:\n{concatenated_1d}")
print(f"Shape: {concatenated_1d.shape}")
print("-" * 30)

# --- Example 2: Concatenating 2D Tensors along a dimension ---
# Create two 2D tensors with compatible shapes
tensor1_2d = torch.arange(1, 7).reshape(2, 3)
tensor2_2d = torch.arange(7, 13).reshape(2, 3)
print("--- Example 2: 2D Tensors ---")
print(f"Tensor 1 (2x3):\n{tensor1_2d}")
print(f"Tensor 2 (2x3):\n{tensor2_2d}\n")

# Concatenate along dimension 0 (rows)
# This stacks the tensors vertically. The number of columns must match.
concatenated_dim0 = torch.cat((tensor1_2d, tensor2_2d), dim=0)
print(f"Concatenated along dim=0 (stacks vertically):\n{concatenated_dim0}")
print(f"Shape: {concatenated_dim0.shape}\n")

# Concatenate along dimension 1 (columns)
# This joins the tensors horizontally. The number of rows must match.
concatenated_dim1 = torch.cat((tensor1_2d, tensor2_2d), dim=1)
print(f"Concatenated along dim=1 (joins horizontally):\n{concatenated_dim1}")
print(f"Shape: {concatenated_dim1.shape}")
print("-" * 30)

tile

In [ ]:
# This script demonstrates the use of torch.tile() for repeating tensors.

import torch

# --- Example 1: Tiling a 1D tensor ---
# Create a 1D tensor
original_tensor = torch.tensor([1, 2, 3])
print("--- Example 1: Tiling a 1D Tensor ---")
print(f"Original Tensor: {original_tensor}")
print(f"Original Shape: {original_tensor.shape}\n")

# Tile the tensor once along its single dimension.
# This is equivalent to just getting the original tensor.
tiled_tensor_1 = torch.tile(original_tensor, (1,))
print(f"Tiled with dims=(1,): {tiled_tensor_1}")
print(f"New Shape: {tiled_tensor_1.shape}\n")

# Tile the tensor 3 times along its single dimension.
# The result will be a 1D tensor with 3x the original length.
tiled_tensor_3 = torch.tile(original_tensor, (3,))
print(f"Tiled with dims=(3,): {tiled_tensor_3}")
print(f"New Shape: {tiled_tensor_3.shape}\n")
print("-" * 30)

# --- Example 2: Tiling a 2D tensor ---
# Create a 2D tensor
original_2d_tensor = torch.tensor([[1, 2], [3, 4]])
print("--- Example 2: Tiling a 2D Tensor ---")
print(f"Original 2D Tensor:\n{original_2d_tensor}")
print(f"Original Shape: {original_2d_tensor.shape}\n")

# Tile the tensor once in the row dimension and 3 times in the column dimension.
# The `dims` tuple must match the number of dimensions in the original tensor.
# (num_row_repeats, num_col_repeats)
tiled_2d_1x3 = torch.tile(original_2d_tensor, (1, 3))
print(f"Tiled with dims=(1, 3):\n{tiled_2d_1x3}")
print(f"New Shape: {tiled_2d_1x3.shape}\n")

# Tile the tensor 2 times in the row dimension and 1 time in the column dimension.
tiled_2d_2x1 = torch.tile(original_2d_tensor, (2, 1))
print(f"Tiled with dims=(2, 1):\n{tiled_2d_2x1}")
print(f"New Shape: {tiled_2d_2x1.shape}\n")

# Tile the tensor 2 times in the row dimension and 3 times in the column dimension.
tiled_2d_2x3 = torch.tile(original_2d_tensor, (2, 3))
print(f"Tiled with dims=(2, 3):\n{tiled_2d_2x3}")
print(f"New Shape: {tiled_2d_2x3.shape}")
print("-" * 30)

# --- Example 3: Tiling with Broadcasting ---
# When the `dims` tuple has more elements than the tensor's dimensions,
# the original tensor is implicitly treated as if it had new leading dimensions
# of size 1.
print("--- Example 3: Tiling with Broadcasting ---")
print(f"Original 2D Tensor:\n{original_2d_tensor}")
print(f"Original Shape: {original_2d_tensor.shape}\n")

# The dims tuple (3, 2, 1) has 3 elements.
# The 2D tensor is first treated as a 3D tensor of shape (1, 2, 2)
# and then tiled accordingly.
tiled_broadcast = torch.tile(original_2d_tensor, (3, 2, 1))
print(f"Tiled with dims=(3, 2, 1):\n{tiled_broadcast}")
print(f"New Shape: {tiled_broadcast.shape}")


torch.Split

In [ ]:
# This script demonstrates how to use torch.split() to divide a tensor.

import torch

# --- Example 1: Splitting a 1D Tensor into equal-sized chunks ---
print("--- Example 1: Splitting a 1D Tensor ---")

# Create a 1D tensor with 12 elements
tensor_1d = torch.arange(12)
print(f"Original 1D Tensor:\n{tensor_1d}")
print(f"Original Shape: {tensor_1d.shape}\n")

# Split the tensor into 3 equal parts (chunks of size 4)
split_tensors_equal = torch.split(tensor_1d, split_size_or_sections=4)
print(f"Splitting into equal-sized chunks (size=4):")
for i, t in enumerate(split_tensors_equal):
    print(f"  Chunk {i+1}: {t}")
print(f"Number of resulting tensors: {len(split_tensors_equal)}\n")

# Split the tensor using a list of sizes
split_tensors_list = torch.split(tensor_1d, split_size_or_sections=[2, 5, 5])
print(f"Splitting with a list of sizes ([2, 5, 5]):")
for i, t in enumerate(split_tensors_list):
    print(f"  Chunk {i+1}: {t}")
print("-" * 30)

# --- Example 2: Splitting a 2D Tensor along a dimension ---
print("--- Example 2: Splitting a 2D Tensor ---")

# Create a 2D tensor (4x6)
tensor_2d = torch.arange(24).reshape(4, 6)
print(f"Original 2D Tensor (4x6):\n{tensor_2d}\n")

# Split along dimension 0 (the row dimension) into 2 equal-sized chunks
split_rows = torch.split(tensor_2d, split_size_or_sections=2, dim=0)
print("Splitting along dim=0 (rows) into 2 chunks of size 2:")
print(f"  Chunk 1:\n{split_rows[0]}")
print(f"  Chunk 2:\n{split_rows[1]}\n")

# Split along dimension 1 (the column dimension) into chunks of size 3
split_cols = torch.split(tensor_2d, split_size_or_sections=3, dim=1)
print("Splitting along dim=1 (columns) into 2 chunks of size 3:")
print(f"  Chunk 1:\n{split_cols[0]}")
print(f"  Chunk 2:\n{split_cols[1]}")


--- Example 1: Splitting a 1D Tensor ---
Original 1D Tensor:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Original Shape: torch.Size([12])

Splitting into equal-sized chunks (size=4):
  Chunk 1: tensor([0, 1, 2, 3])
  Chunk 2: tensor([4, 5, 6, 7])
  Chunk 3: tensor([ 8,  9, 10, 11])
Number of resulting tensors: 3

Splitting with a list of sizes ([2, 5, 5]):
  Chunk 1: tensor([0, 1])
  Chunk 2: tensor([2, 3, 4, 5, 6])
  Chunk 3: tensor([ 7,  8,  9, 10, 11])
------------------------------
--- Example 2: Splitting a 2D Tensor ---
Original 2D Tensor (4x6):
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

Splitting along dim=0 (rows) into 2 chunks of size 2:
  Chunk 1:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
  Chunk 2:
tensor([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

Splitting along dim=1 (columns) into 2 chunks of size 3:
  Chunk 1:
tensor([