In [2]:
import numpy as np
from typing import Type, List, Any
from PIL import Image
import statistics
import requests
import io as b_io
import cv2
import unittest
import PIL
import sys
import os
import abc
from abc import ABC
import pandas
import pandas as pd
import shutil
import glob
import copy
import pickle
import albumentations
import seaborn as sns
import matplotlib.pyplot as plt
from albumentations import augmentations
from enum import Enum
from skimage import data
from typing import Iterable, Union, Set, Any, Optional, Any, Callable, Sized
from torch.utils.tensorboard import SummaryWriter
import torch
import torch.utils
import torch.utils.data
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
NoneType = type(None)
import common
from common import get_logger, deprecated, DevNull
from common.data.datasets_info import ABCDatasetInfo
from common.data.generic_dataset import GenericDataset, get_generic_dataset, get_generic_dataloader
from common.elements.model.basic import dynamic_load_weights_pt
from common.elements.visualize import hyperspectral_to_rgb
logger = get_logger('notebook_logs')

import numpy as np

<h1 id="exercise-1"><strong>Exercise 1</strong></h1>


<font size="4px"><p>This method calculates the matrix or vector L2 norm.</p>
<dl>
<dt>param x</dt>
<dd>
input array
</dd>
<dt>return</dt>
<dd>
norm of the matrix or vector(s)
</dd>
<dt>example</dt>
<dd>
Calculate the norm of the input array.
</dd>
</dl>
</font>

In [5]:
# Please add code to this function to complete the assignment.
# You can use the description and code cells below to check you answer.
# Tip: With print('hello') you can print debugging info.

def norm(x: np.ndarray):
    # Add/adjust code.
    answer = np.linalg.norm(x)
    print (x)
    print(n)
    return np.linalg.norm(x)

In [6]:
# This cell performs a doctest of the function.
x = np.arange(9).reshape((3, 3))
n = norm(x)
newline = '\n'
your_answer = repr(round(n, 2)).strip()
real_answer = str("14.28")
assert your_answer == real_answer, f'Wrong output, see details below. {newline}{newline}Your answer {newline}{newline}({your_answer}){newline}{newline}Desired answer {newline}{newline}({real_answer}){newline}{newline}'
print('<Test succeeded!>')

[[0 1 2]
 [3 4 5]
 [6 7 8]]
14.2828568570857
<Test succeeded!>


<h1 id="exercise-2"><strong>Exercise 2</strong></h1>


<font size="4px"><p>This method calculates the inner product.</p>
<dl>
<dt>param x1</dt>
<dd>
input array
</dd>
<dt>param x2</dt>
<dd>
input array
</dd>
<dt>return</dt>
<dd>
inner product of x1 and x2
</dd>
<dt>example</dt>
<dd>
Calculate the inner product of the input arrays.
</dd>
</dl>
</font>

In [15]:
# Please add code to this function to complete the assignment.
# You can use the description and code cells below to check you answer.
# Tip: With print('hello') you can print debugging info.

def inner_product(x1: np.ndarray, x2: np.ndarray) -> np.ndarray:
    # Add/adjust code.
    answer = np.dot(x1, x2.T)
    print (x1)
    print (x2)
    print('asnwer')
    print (answer)
    return np.dot(x1, x2.T)

In [16]:
# This cell performs a doctest of the function.
x1 = np.arange(9).reshape((3, 3))
x2 = np.arange(6).reshape((2, 3))
newline = '\n'
your_answer = repr(inner_product(x1, x2)).strip()
real_answer = str("array([[ 5, 14],\n       [14, 50],\n       [23, 86]])")
assert your_answer == real_answer, f'Wrong output, see details below. {newline}{newline}Your answer {newline}{newline}({your_answer}){newline}{newline}Desired answer {newline}{newline}({real_answer}){newline}{newline}'
print('<Test succeeded!>')

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]]
asnwer
[[ 5 14]
 [14 50]
 [23 86]]
<Test succeeded!>


<h1 id="exercise-3"><strong>Exercise 3</strong></h1>


<font size="4px"><p>This method checks if the input matrix is orthogonal.</p>
<dl>
<dt>param x</dt>
<dd>
input matrix
</dd>
<dt>return</dt>
<dd>
True or False
</dd>
<dt>example</dt>
<dd>
Check if the input array is orthogonal.
</dd>
</dl>
</font>

<font size="4px">
</font>

In [26]:
# Please add code to this function to complete the assignment.
# You can use the description and code cells below to check you answer.
# Tip: With print('hello') you can print debugging info.

def is_orthogonal(x: np.ndarray) -> bool:
    # Add/adjust code.
    n = x.shape[0]
    print (n)
    print(x1)
    answer = np.allclose(x @ x.T, np.eye(n),atol=1e-10)
    print (answer)
    return answer

In [27]:
# This cell performs a doctest of the function.
x1 = np.zeros((3, 3))
np.fill_diagonal(x1, 1)
newline = '\n'
your_answer = repr(is_orthogonal(x1)).strip()
real_answer = str("True")
assert your_answer == real_answer, f'Wrong output, see details below. {newline}{newline}Your answer {newline}{newline}({your_answer}){newline}{newline}Desired answer {newline}{newline}({real_answer}){newline}{newline}'
print('<Test succeeded!>')

3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
True
<Test succeeded!>


In [28]:
# This cell performs a doctest of the function.
x2 = np.arange(9).reshape((3, 3))
newline = '\n'
your_answer = repr(is_orthogonal(x2)).strip()
real_answer = str("False")
assert your_answer == real_answer, f'Wrong output, see details below. {newline}{newline}Your answer {newline}{newline}({your_answer}){newline}{newline}Desired answer {newline}{newline}({real_answer}){newline}{newline}'
print('<Test succeeded!>')

3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
False
<Test succeeded!>


<h1 id="exercise-4"><strong>Exercise 4</strong></h1>


<font size="4px"><p>This method projects one input vector onto another input vector.</p>
<dl>
<dt>param x</dt>
<dd>
input vector
</dd>
<dt>param y</dt>
<dd>
input vector
</dd>
<dt>return</dt>
<dd>
projection of vector x onto vector y
</dd>
<dt>example</dt>
<dd>

</dd>
</dl>
</font>

In [49]:
# Please add code to this function to complete the assignment.
# You can use the description and code cells below to check you answer.
# Tip: With print('hello') you can print debugging info.

def projection(x: np.ndarray, y: np.ndarray):
    # Add/adjust code.
    print(x)
    print(y)
    print('hello')
    answer = np.round((np.dot(x, y) / np.dot(y, y)) * y, 3)
    print(answer)
    return answer

In [50]:
# This cell performs a doctest of the function.
x = np.array([1,2,3])
y = np.array([-1,2,3])
newline = '\n'
your_answer = repr(np.round(projection(x, y), 3)).strip()
real_answer = str("array([-0.857,  1.714,  2.571])")
assert your_answer == real_answer, f'Wrong output, see details below. {newline}{newline}Your answer {newline}{newline}({your_answer}){newline}{newline}Desired answer {newline}{newline}({real_answer}){newline}{newline}'
print('<Test succeeded!>')

[1 2 3]
[-1  2  3]
hello
[-0.857  1.714  2.571]
<Test succeeded!>


<h1 id="exercise-5"><strong>Exercise 5</strong></h1>


<font size="4px"><p>This method calculates the cosine similarity between two vectors:</p>
<p>\begin{equation*} \cos (\mathbf{A}, \mathbf{B})=\frac{\mathbf{A}
\cdot \mathbf{B}}{|\mathbf{A}||\mathbf{B}|}=\frac{\sum_{i=1}^{n} A_{i}
B_{i}}{\sqrt{\sum_{i=1}^{n} A_{i}^{2}} \sqrt{\sum_{i=1}^{n} B_{i}^{2}}}
\end{equation*}</p>
<dl>
<dt>param v</dt>
<dd>
a vector
</dd>
<dt>param w</dt>
<dd>
a vector
</dd>
<dt>return</dt>
<dd>
a single value denoting the cosine similarity between v and w (interval
[-1, 1])
</dd>
<dt>example</dt>
<dd>
Calculate the inner product of the input vectors pointing in the same
direction.
</dd>
</dl>
</font>

<font size="4px"><dl>
<dt>example</dt>
<dd>
Calculate the inner product of the input vectors pointing in different
directions.
</dd>
</dl>
</font>

In [54]:
# Please add code to this function to complete the assignment.
# You can use the description and code cells below to check you answer.
# Tip: With print('hello') you can print debugging info.

def cosine_similarity(v: np.ndarray, w: np.ndarray):
    # Add/adjust code.
    print(v)
    print(w)
    answer= np.around(np.dot(v, w) / (np.linalg.norm(v) * np.linalg.norm(w)),3)
    print(answer)
    return answer

In [55]:
# This cell performs a doctest of the function.
v = np.array([1,2,3])
w = np.array([1,2,3])
newline = '\n'
your_answer = repr(cosine_similarity(v, w)).strip()
real_answer = str("1.0")
assert your_answer == real_answer, f'Wrong output, see details below. {newline}{newline}Your answer {newline}{newline}({your_answer}){newline}{newline}Desired answer {newline}{newline}({real_answer}){newline}{newline}'
print('<Test succeeded!>')

[1 2 3]
[1 2 3]
1.0
<Test succeeded!>


In [56]:
# This cell performs a doctest of the function.
v = np.array([1,2,3])
w = np.array([1,-2,3])
newline = '\n'
your_answer = repr(np.round(cosine_similarity(v, w), 3)).strip()
real_answer = str("0.429")
assert your_answer == real_answer, f'Wrong output, see details below. {newline}{newline}Your answer {newline}{newline}({your_answer}){newline}{newline}Desired answer {newline}{newline}({real_answer}){newline}{newline}'
print('<Test succeeded!>')

[1 2 3]
[ 1 -2  3]
0.429
<Test succeeded!>
