In [2]:
import numpy as np
from typing import Type, List, Any
from PIL import Image
import statistics
import requests
import io as b_io
import cv2
import unittest
import PIL
import sys
import os
import abc
from abc import ABC
import pandas
import pandas as pd
import shutil
import glob
import copy
import pickle
import albumentations
import seaborn as sns
import matplotlib.pyplot as plt
from albumentations import augmentations
from enum import Enum
from skimage import data
from typing import Iterable, Union, Set, Any, Optional, Any, Callable, Sized
from torch.utils.tensorboard import SummaryWriter
import torch
import torch.utils
import torch.utils.data
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
NoneType = type(None)
import common
from common import get_logger, deprecated, DevNull
from common.data.datasets_info import ABCDatasetInfo
from common.data.generic_dataset import GenericDataset, get_generic_dataset, get_generic_dataloader
from common.elements.model.basic import dynamic_load_weights_pt
from common.elements.visualize import hyperspectral_to_rgb
logger = get_logger('notebook_logs')

import numpy as np

<h1 id="exercise-1"><strong>Exercise 1</strong></h1>


<font size="4px"><p>This method calculates the transpose of a matrix.</p>
<dl>
<dt>param arr</dt>
<dd>
input matrix
</dd>
<dt>return</dt>
<dd>
transposed input matrix
</dd>
<dt>example</dt>
<dd>
Apply a transpose on the input array.
</dd>
</dl>
</font>

In [14]:
# Please add code to this function to complete the assignment.
# You can use the description and code cells below to check you answer.
# Tip: With print('hello') you can print debugging info.

def transpose(arr: np.ndarray) -> np.ndarray:
    # Add/adjust code.
    #use np.transpose(arr) or arr.T
    print(arr)
    answer = np.transpose(arr)
    print(answer)
    return answer

In [15]:
# This cell performs a doctest of the function.
x = np.arange(4).reshape((2,2))
newline = '\n'
your_answer = repr(transpose(x)).strip()
real_answer = str("array([[0, 2],\n       [1, 3]])")
assert your_answer == real_answer, f'Wrong output, see details below. {newline}{newline}Your answer {newline}{newline}({your_answer}){newline}{newline}Desired answer {newline}{newline}({real_answer}){newline}{newline}'
print('<Test succeeded!>')

[[0 1]
 [2 3]]
[[0 2]
 [1 3]]
<Test succeeded!>


<h1 id="exercise-2"><strong>Exercise 2</strong></h1>


<font size="4px"><p>This method calculates the inverse of a matrix.</p>
<dl>
<dt>param arr</dt>
<dd>
input matrix
</dd>
<dt>return</dt>
<dd>
inverse of the input matrix
</dd>
<dt>example</dt>
<dd>
Apply an inverse on the input array.
</dd>
</dl>
</font>

In [12]:
# Please add code to this function to complete the assignment.
# You can use the description and code cells below to check you answer.
# Tip: With print('hello') you can print debugging info.

def inverse(arr: np.ndarray) -> np.ndarray:
    # Add/adjust code.
    answer = np.linalg.inv(arr)
    print (arr)
    print (answer)
    return answer

In [13]:
# This cell performs a doctest of the function.
x = np.arange(4).reshape((2,2))
newline = '\n'
your_answer = repr(inverse(x)).strip()
real_answer = str("array([[-1.5,  0.5],\n       [ 1. ,  0. ]])")
assert your_answer == real_answer, f'Wrong output, see details below. {newline}{newline}Your answer {newline}{newline}({your_answer}){newline}{newline}Desired answer {newline}{newline}({real_answer}){newline}{newline}'
print('<Test succeeded!>')

[[0 1]
 [2 3]]
[[-1.5  0.5]
 [ 1.   0. ]]
<Test succeeded!>


<h1 id="exercise-3"><strong>Exercise 3</strong></h1>


<font size="4px"><p>This method calculates the product of two matrices.</p>
<p>\begin{equation*}y = \mathbf{A} \cdot \mathbf{B}\end{equation*}</p>
<dl>
<dt>param x1</dt>
<dd>
input matrix
</dd>
<dt>param x2</dt>
<dd>
input matrix
</dd>
<dt>return</dt>
<dd>
product of the input matrices
</dd>
<dt>example</dt>
<dd>
Apply a matrix multiplication on the input arrays.
</dd>
</dl>
</font>

In [20]:
# Please add code to this function to complete the assignment.
# You can use the description and code cells below to check you answer.
# Tip: With print('hello') you can print debugging info.

def dot_product(x1: np.ndarray, x2: np.ndarray) -> np.ndarray:
    # Add/adjust code.
    print(x1)
    print(x2)
    answer = np.dot(x1, x2)
    print(answer)
    return answer

In [21]:
# This cell performs a doctest of the function.
x1 = np.arange(4).reshape((2,2))
x2 = np.arange(4).reshape((2,2))
newline = '\n'
your_answer = repr(dot_product(x1, x2)).strip()
real_answer = str("array([[ 2,  3],\n       [ 6, 11]])")
assert your_answer == real_answer, f'Wrong output, see details below. {newline}{newline}Your answer {newline}{newline}({your_answer}){newline}{newline}Desired answer {newline}{newline}({real_answer}){newline}{newline}'
print('<Test succeeded!>')

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]
[[ 2  3]
 [ 6 11]]
<Test succeeded!>


<h1 id="exercise-4"><strong>Exercise 4</strong></h1>


<font size="4px"><p>This method computes the linear combination of inputs and
weights.</p>
<dl>
<dt>param x</dt>
<dd>
the input values
</dd>
<dt>param weights</dt>
<dd>

</dd>
<dt>param bias</dt>
<dd>

</dd>
<dt>return</dt>
<dd>
linear combination of inputs and weights
</dd>
<dt>example</dt>
<dd>

</dd>
</dl>
</font>

In [24]:
# Please add code to this function to complete the assignment.
# You can use the description and code cells below to check you answer.
# Tip: With print('hello') you can print debugging info.

def forward_propagation(x: np.ndarray, weights: np.ndarray, bias: float = -1):
    # Add/adjust code.
    answer = np.dot(x, weights) + bias
    print (answer)
    return answer

In [25]:
# This cell performs a doctest of the function.
x = np.array([[0.2, 0.5, 0.1], [0.1, 0.3, 0.4]])
weights = np.array([-0.5, 0.5, 0.8])
bias = -1
newline = '\n'
your_answer = repr(np.round(forward_propagation(x, weights, bias), 3)).strip()
real_answer = str("array([-0.77, -0.58])")
assert your_answer == real_answer, f'Wrong output, see details below. {newline}{newline}Your answer {newline}{newline}({your_answer}){newline}{newline}Desired answer {newline}{newline}({real_answer}){newline}{newline}'
print('<Test succeeded!>')

[-0.77 -0.58]
<Test succeeded!>


<h1 id="exercise-5"><strong>Exercise 5</strong></h1>


<font size="4px"><p>This method computes the closed-form solution of linear regression
when an input matrix and target vector is known.</p>
<p>\begin{equation*}\hat{\mathbf{w}} = \left(\mathbf{X}^{\mathrm{T}}
\mathbf{X}\right)^{-1} \mathbf{X}^{\mathrm{T}} \mathbf{y}
\end{equation*}</p>
<p>You may assume that the input data is linearly seperable.</p>
<dl>
<dt>param x</dt>
<dd>
an input matrix in which each row is a data point
</dd>
<dt>param target</dt>
<dd>
an input vector in which each value corresponds to a target output
</dd>
<dt>return</dt>
<dd>
an output vector holding the coefficient weights of the linear
regression
</dd>
<dt>example</dt>
<dd>

</dd>
</dl>
</font>

In [26]:
# Please add code to this function to complete the assignment.
# You can use the description and code cells below to check you answer.
# Tip: With print('hello') you can print debugging info.

def compute_weights(x: np.ndarray, target: np.ndarray) -> np.ndarray:
    # Add/adjust code.
    
    return np.linalg.inv(x.T @ x) @ x.T @ target

In [27]:
# This cell performs a doctest of the function.
x = np.array([[1, 0, 1], [1, 1, 0], [1, 0, 0]])
target = np.array([1, 1, 0])
newline = '\n'
your_answer = repr(np.abs(np.round(compute_weights(x, target), 5))).strip()
real_answer = str("array([0., 1., 1.])")
assert your_answer == real_answer, f'Wrong output, see details below. {newline}{newline}Your answer {newline}{newline}({your_answer}){newline}{newline}Desired answer {newline}{newline}({real_answer}){newline}{newline}'
print('<Test succeeded!>')

<Test succeeded!>
