In [2]:
import numpy as np
from typing import Type, List, Any
from PIL import Image
import statistics
import requests
import io as b_io
import cv2
import unittest
import PIL
import sys
import os
import abc
from abc import ABC
import pandas
import pandas as pd
import shutil
import glob
import copy
import pickle
import albumentations
import seaborn as sns
import matplotlib.pyplot as plt
from albumentations import augmentations
from enum import Enum
from skimage import data
from typing import Iterable, Union, Set, Any, Optional, Any, Callable, Sized
from torch.utils.tensorboard import SummaryWriter
import torch
import torch.utils
import torch.utils.data
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
NoneType = type(None)
import common
from common import get_logger, deprecated, DevNull
from common.data.datasets_info import ABCDatasetInfo
from common.data.generic_dataset import GenericDataset, get_generic_dataset, get_generic_dataloader
from common.elements.model.basic import dynamic_load_weights_pt
from common.elements.visualize import hyperspectral_to_rgb
logger = get_logger('notebook_logs')

import numpy as np

<h1 id="exercise-1"><strong>Exercise 1</strong></h1>


<font size="4px"><p>This method calculates the determinant of a matrix.</p>
<dl>
<dt>param x</dt>
<dd>
input matrix
</dd>
<dt>return</dt>
<dd>
determinant of the input matrix
</dd>
<dt>example</dt>
<dd>
Calculate the determinant of the input array.
</dd>
</dl>
</font>

In [7]:
# Please add code to this function to complete the assignment.
# You can use the description and code cells below to check you answer.
# Tip: With print('hello') you can print debugging info.

def determinant(x: np.ndarray):
    # Add/adjust code.
    print(x)
    answer = np.round(np.linalg.det(x),2)
    print(answer)
    return answer

In [8]:
# This cell performs a doctest of the function.
x = np.array([[1, 2], [3, 4]])
d = determinant(x)
newline = '\n'
your_answer = repr(round(d, 2)).strip()
real_answer = str("-2.0")
assert your_answer == real_answer, f'Wrong output, see details below. {newline}{newline}Your answer {newline}{newline}({your_answer}){newline}{newline}Desired answer {newline}{newline}({real_answer}){newline}{newline}'
print('<Test succeeded!>')

[[1 2]
 [3 4]]
-2.0
<Test succeeded!>


<h1 id="exercise-2"><strong>Exercise 2</strong></h1>


<font size="4px"><p>These methods check if the input matrix is invertible.</p>
<dl>
<dt>param x</dt>
<dd>
input matrix
</dd>
<dt>return</dt>
<dd>
True if matrix is invertible, False otherwise.
</dd>
<dt>example</dt>
<dd>

</dd>
</dl>
</font>

In [23]:
# Please add code to this function to complete the assignment.
# You can use the description and code cells below to check you answer.
# Tip: With print('hello') you can print debugging info.
from numpy.linalg import inv

def is_invertible(x: np.ndarray):
    # Add/adjust code.
    print(x)
    t = inv(x)
    print (t)
    answer = np.allclose(x @ t, np.eye(2))
    print (answer)
    return answer

In [24]:
# This cell performs a doctest of the function.
x = np.array([[1, 2], [3, 4]])
newline = '\n'
your_answer = repr(is_invertible(x)).strip()
real_answer = str("True")
assert your_answer == real_answer, f'Wrong output, see details below. {newline}{newline}Your answer {newline}{newline}({your_answer}){newline}{newline}Desired answer {newline}{newline}({real_answer}){newline}{newline}'
print('<Test succeeded!>')

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
True
<Test succeeded!>


In [ ]:
# This cell performs a doctest of the function.
x = np.array([[0, 0], [0, 0]])
newline = '\n'
your_answer = repr(is_invertible(x)).strip()
real_answer = str("False")
assert your_answer == real_answer, f'Wrong output, see details below. {newline}{newline}Your answer {newline}{newline}({your_answer}){newline}{newline}Desired answer {newline}{newline}({real_answer}){newline}{newline}'
print('<Test succeeded!>')

In [ ]:
# This cell performs a doctest of the function.
x = np.array([[0, -1], [0, 3]])
newline = '\n'
your_answer = repr(is_invertible(x)).strip()
real_answer = str("False")
assert your_answer == real_answer, f'Wrong output, see details below. {newline}{newline}Your answer {newline}{newline}({your_answer}){newline}{newline}Desired answer {newline}{newline}({real_answer}){newline}{newline}'
print('<Test succeeded!>')

<h1 id="exercise-3"><strong>Exercise 3</strong></h1>


<font size="4px"><p>This method calculates the trace of a matrix.</p>
<dl>
<dt>param x</dt>
<dd>
input matrix
</dd>
<dt>return</dt>
<dd>
trace of the input matrix.
</dd>
<dt>example</dt>
<dd>
Calculate the trace of the input array.
</dd>
</dl>
</font>

In [31]:
# Please add code to this function to complete the assignment.
# You can use the description and code cells below to check you answer.
# Tip: With print('hello') you can print debugging info.

def trace(x: np.ndarray):
    # Add/adjust code.
    answer = np.trace(x)
    print(x)
    print (answer)
    return answer

In [32]:
# This cell performs a doctest of the function.
x = np.array([[1, 2], [3, 4]])
newline = '\n'
your_answer = repr(trace(x)).strip()
real_answer = str("5")
assert your_answer == real_answer, f'Wrong output, see details below. {newline}{newline}Your answer {newline}{newline}({your_answer}){newline}{newline}Desired answer {newline}{newline}({real_answer}){newline}{newline}'
print('<Test succeeded!>')

[[1 2]
 [3 4]]
5
<Test succeeded!>


<h1 id="exercise-4"><strong>Exercise 4</strong></h1>


<font size="4px"><p>This method calculates the eigenvalues of a matrix.</p>
<dl>
<dt>param x</dt>
<dd>
input matrix of size (MxM)
</dd>
<dt>return</dt>
<dd>
eigenvalues
</dd>
<dt>example</dt>
<dd>

</dd>
</dl>
</font>

In [41]:
# Please add code to this function to complete the assignment.
# You can use the description and code cells below to check you answer.
# Tip: With print('hello') you can print debugging info.

def eigenvalues(x: np.ndarray) -> np.ndarray:
    # Add/adjust code.
    print(x)
    answer = np.linalg.eigvals(x)
    print(answer)
    return answer

In [42]:
# This cell performs a doctest of the function.
x = np.array([[4, 1], [2, 3]])
newline = '\n'
your_answer = repr(eigenvalues(x)).strip()
real_answer = str("array([5., 2.])")
assert your_answer == real_answer, f'Wrong output, see details below. {newline}{newline}Your answer {newline}{newline}({your_answer}){newline}{newline}Desired answer {newline}{newline}({real_answer}){newline}{newline}'
print('<Test succeeded!>')

[[4 1]
 [2 3]]
[5. 2.]
<Test succeeded!>


<h1 id="exercise-5"><strong>Exercise 5</strong></h1>


<font size="4px"><p>This method computes the eigenvectors of a matrix.</p>
<dl>
<dt>param x</dt>
<dd>
input matrix of size (MxM)
</dd>
<dt>return</dt>
<dd>
output matrix of size (MxM) representing the right eigenvectors of the
square matrix
</dd>
<dt>example</dt>
<dd>

</dd>
</dl>
</font>

In [43]:
# Please add code to this function to complete the assignment.
# You can use the description and code cells below to check you answer.
# Tip: With print('hello') you can print debugging info.

def eigenvectors(x: np.ndarray):
    # Add/adjust code.
    eigenvalues, eigenvectors = np.linalg.eig(x)
    return eigenvectors

In [44]:
# This cell performs a doctest of the function.
x = np.array([[4, 1], [2, 3]])
newline = '\n'
your_answer = repr(np.round(eigenvectors(x), 3)).strip()
real_answer = str("array([[ 0.707, -0.447],\n       [ 0.707,  0.894]])")
assert your_answer == real_answer, f'Wrong output, see details below. {newline}{newline}Your answer {newline}{newline}({your_answer}){newline}{newline}Desired answer {newline}{newline}({real_answer}){newline}{newline}'
print('<Test succeeded!>')

<Test succeeded!>
